### ISSUE TITLE
Blurred images when using batch count: 4 with sharpness: 1

### ISSUE THREAD

**Issue by abvgdeabvgde2** [Haoming02/sd-webui-resharpen#13] opened 2024-08-31 19:49 UTC
### UI
Forge

### Model
Flux.1-dev

### Batch Count
3+

### ReSharpen Sharpness
1

### Description
Images produced by the system become increasingly blurred as the batch count increases. This issue is noticeable even when generating images with 5 sampling steps. Increasing the batch size does not trigger this bug; only the batch count affects the image sharpness.

### Sample output
https://i.imgur.com/RXwZo2U.jpeg

Formatting powered by GPT 😆

**Comment by Haoming02** [comment] 2024-09-02 04:07
Does this problem only occur with Flux models? Cause I tried with SD 1.5 ones and couldn't reproduce.

Though I also pushed a commit that might fix it.

**Comment by abvgdeabvgde2** [comment] 2024-09-02 20:33
> Does this problem only occur with Flux models?

I think so. It seems like it's fixed now on Flux as well.

**Comment by Haoming02** [comment] 2024-09-03 01:19
Oh nice. I'll close the issue then.

**Closed by Haoming02** 2024-09-03 01:19 UTC
